export const ROOT_RUNTIME_EXPORTS = [
  "CODE_ABBREVIATIONS",
  "allGatesPassed",
  "applyMigrations",
  "applyRerankers",
  "bm25Score",
  "buildBM25Context",
  "buildExplanation",
  "buildIndex",
  "classify",
  "closePg",
  "closeSqlite",
  "computeHybridScore",
  "cosineSimilarity",
  "createPgStoreOps",
  "createSqliteStoreOps",
  "deepMerge",
  "deserializeEmbedding",
  "evaluateGates",
  "expandQuery",
  "extractTopTerms",
  "getCurrentSchemaVersion",
  "getGlobalConfigPath",
  "getLatestMigrationVersion",
  "getPg",
  "getSessionId",
  "getSqlite",
  "hashPath",
  "hitRateAtK",
  "initLogging",
  "kmeans",
  "kmeansSearch",
  "loadConfig",
  "logEvent",
  "mrr",
  "ndcg",
  "pgToSqlite",
  "pgUnsafe",
  "precisionAtK",
  "recall",
  "sampleRepresentative",
  "serializeEmbedding",
  "setCorrelationContext",
  "silhouetteScore",
  "tokenize",
  "voteAll",
  "voteDeepest",
  "voteMostSpecific",
  "voteSubset",
  "withTimingAsync",
  "withTimingSync",
  "writeGlobalConfig",
] as const;

export const SUBPATH_CONTRACT = [
  {
    exportKey: "./db",
    specifier: "@easier/core/db",
    runtimeExports: [
      "cosineSimilarity",
      "deserializeEmbedding",
      "serializeEmbedding",
    ] as const,
  },
  {
    exportKey: "./db/store",
    specifier: "@easier/core/db/store",
    runtimeExports: [
      "createPgStoreOps",
      "createSqliteStoreOps",
      "pgToSqlite",
    ] as const,
  },
  {
    exportKey: "./db/sqlite",
    specifier: "@easier/core/db/sqlite",
    runtimeExports: ["closeSqlite", "getSqlite"] as const,
  },
  {
    exportKey: "./db/pg",
    specifier: "@easier/core/db/pg",
    runtimeExports: ["closePg", "getPg", "pgUnsafe"] as const,
  },
  {
    exportKey: "./db/migrate",
    specifier: "@easier/core/db/migrate",
    runtimeExports: [
      "applyMigrations",
      "getCurrentSchemaVersion",
      "getLatestMigrationVersion",
      "migrationChecksum",
    ] as const,
  },
  {
    exportKey: "./search",
    specifier: "@easier/core/search",
    runtimeExports: ["buildExplanation", "computeHybridScore"] as const,
  },
  {
    exportKey: "./search/bm25",
    specifier: "@easier/core/search/bm25",
    runtimeExports: ["buildIndex", "score", "tokenize"] as const,
  },
  {
    exportKey: "./search/bm25-helpers",
    specifier: "@easier/core/search/bm25-helpers",
    runtimeExports: ["buildBM25Context"] as const,
  },
  {
    exportKey: "./eval/gate",
    specifier: "@easier/core/eval/gate",
    runtimeExports: ["allGatesPassed", "evaluateGates"] as const,
  },
  {
    exportKey: "./eval/metrics",
    specifier: "@easier/core/eval/metrics",
    runtimeExports: [
      "hitRateAtK",
      "mrr",
      "ndcg",
      "precisionAtK",
      "recall",
    ] as const,
  },
  {
    exportKey: "./config",
    specifier: "@easier/core/config",
    runtimeExports: [
      "deepMerge",
      "getGlobalConfigPath",
      "loadConfig",
      "writeGlobalConfig",
    ] as const,
  },
  {
    exportKey: "./cluster",
    specifier: "@easier/core/cluster",
    runtimeExports: ["kmeans", "kmeansSearch"] as const,
  },
  {
    exportKey: "./cluster/classify",
    specifier: "@easier/core/cluster/classify",
    runtimeExports: [
      "classify",
      "voteAll",
      "voteDeepest",
      "voteMostSpecific",
      "voteSubset",
    ] as const,
  },
  {
    exportKey: "./cluster/silhouette",
    specifier: "@easier/core/cluster/silhouette",
    runtimeExports: ["silhouetteScore"] as const,
  },
  {
    exportKey: "./cluster/describe",
    specifier: "@easier/core/cluster/describe",
    runtimeExports: ["extractTopTerms", "sampleRepresentative"] as const,
  },
] as const;

export const ROOT_TYPE_EXPORTS = [
  "BM25Context",
  "BM25Index",
  "BoostTerm",
  "Collector",
  "Cluster",
  "ClusterAssignment",
  "ClusterDef",
  "ClusterProvider",
  "ClusterResult",
  "ClassifyOptions",
  "ClassifyResult",
  "Document",
  "DocumentStore",
  "EasierConfig",
  "EvalQuery",
  "EvalResult",
  "EvalSummary",
  "GateResult",
  "HybridScoreInput",
  "KMeansOptions",
  "LabeledItem",
  "PgConfig",
  "PipelineResult",
  "QualityGate",
  "QueryRewriteContext",
  "QueryRewriter",
  "RerankConfig",
  "Reranker",
  "ScoreExplanation",
  "ScoringConfig",
  "SearchResult",
  "SqlRunner",
  "SqliteConfig",
  "StoreOps",
  "VotingStrategy",
] as const;
